### ISSUE TITLE
Add a method for capturing donations where the donor doesn't return to the Donation Confirmation page.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give-Google-Analytics#13]
## Issue overview
Currently donations are only recorded in Google Analytics when the donor returns to the Donation Confirmation page. This causes incomplete records for PayPal standard donations.

## Potential fix
Record it based on IPN callback.

**Comment by DevinWalker** [comment]
This has been resolved - see `give_google_analytics_handle_offsite_gateways()` within https://github.com/WordImpress/Give-Google-Analytics/blob/master/includes/give-google-analytics-functions.php#L440
