### ISSUE TITLE
Incompatibility with popular GA Plugin

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give-Google-Analytics#14]
## Issue overview

The addon does not appear to work with this GA plugin, in my tests, and also reported by a user.

https://wordpress.org/plugins/google-analytics-dashboard-for-wp/

If you find that it does work, please give me step by step instructions how to set it up. :-)

**Comment by Benunc** [comment]
customer waiting on feedback here: https://secure.helpscout.net/conversation/403548579/0/?folderId=848135

**Comment by DevinWalker** [comment]
This is working fine on my testing. Please reopen if you have any other customers reporting the problem! Thanks
