### ISSUE TITLE
Add an ID to the script tag so we can more easily identify it on page

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Google-Analytics#15]
Would love to be able to more easily troubleshoot GA issues by just searching on page for `id="give_ga_ec_script"` or something like that.

Just add here:
https://github.com/WordImpress/Give-Google-Analytics/blob/master/includes/give-google-analytics-functions.php#L158 

Like this: 
`<script type="text/javascript" id="give_ga_ec_script">`

**Comment by DevinWalker** [comment]
Why don't you just search for `give_ga_purchase` or another unique string in that script?

**Comment by mathetos** [comment]
I could. That's a fair point. My thought was just that easily identifying exactly why a certain inline script is displayed on that page would be useful, even for Give Core or other Add-ons as well. Searching for `give_ga_` could work fine, and I doubt there'd be other plugins outputting something like that, so I'm fine closing this for now.
