### ISSUE TITLE
Make the donation view event a non-interacting event.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give-Google-Analytics#16]
## Issue overview

Our addon is creating an interaction event, which is messing with bounce rates. Here's the helpful ticket from a user:

> We installed your Google Analytics Donation Tracking add-on as soon as our site launched. Our bounce rate immediately went from 85, which is an indication that something has gone wrong.
> It took me a long time to realize that your GA add-on was what was causing the problem. Your plugin uses this JS code:
> 
> ga( 'send', 'event', 'Fundraising', 'Donation Form View', form_title );
> 
> We have a Give form embedded on our front page, and on every other page of the site. I *think* what's happening is that immediately upon loading the page, the "Donation Form View" event is sent, which is an "interaction" event that counts against bounce rate.
> 
> What I'm saying is that your add-on, by default, makes bounce rate measurements essentially meaningless by making any page view count as "not a bounce." Please consider changing this to make the donation form view a non-interaction event (https://developers.google.com/analytics/devguides/collection/analyticsjs/events#non-interaction_events).
> 

We should fix that.

**Comment by Benunc** [comment]
ticket for future reference: https://secure.helpscout.net/conversation/447691008/10865/

**Comment by mathetos** [comment]
That's really interesting. I think the thing is that filling out a donation form IS a interacting event. If you land on a donation form page, the intention is to donate. But I can see that sometimes they put a donation form on their whole site. That could be problematic.

Seems we'd want to toggle which pages have the interaction event and which don't. Perhaps we can do that for ONLY the single donation form pages and exclude it on the widget and shortcode.

**Comment by DevinWalker** [comment]
That makes sense @Benunc - I'm releasing this now in 1.1.1 - see commit above for details

**Comment by Benunc** [comment]
@DevinWalker I'm still seeing 1.1 live on the site, make sure to release it all the way!

**Comment by DevinWalker** [comment]
@Benunc released!
