### ISSUE TITLE
Licensing check doesn't work as intended

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Google-Analytics#20]
We just confirmed that the update nag does not appear for users on version 1.1.2. My assumption is that it won't work for 1.1.3 either. See screencast here:
http://somup.com/cFe1YOVAZW

**Comment by DevinWalker** [comment]
If you don't have an active license the updates will not display currently. You need to activate a license to see it: 

![2018-03-06_15-19-32](https://user-images.githubusercontent.com/1571635/37064432-cb81b064-2151-11e8-9952-a1ec173032de.png)

This is getting resolved in Give core with the licensing refactor.
