### ISSUE TITLE
fix(bug): stop stripping off Traffic source and Medium for donation event-related visits

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give-Google-Analytics#21]
## Issue Description
When our add-on is active, the source and medium is stripped off of all traffic related to a Give event.

## Current Behavior
https://screencast-o-matic.com/watch/cFejoADoaj

After the video, I confirmed that traffic to a page without a Give form on it did not produce the issue. It seems like the actual donation is what triggers the stripping, as was seen in the video.

Simply visiting a form appears to be OK. but submitting a donation makes the traffic source disappear.

Multiple users have reported this.

**Comment by DevinWalker** [comment]
Nice video @Benunc - I will review and resolve

**Comment by raftaar1191** [comment]
UTM Parameters Examples: https://blog.kissmetrics.com/how-to-use-utm-parameters/
