### ISSUE TITLE
fix(give-google-analytics): Plugin conflict with Give Google Analytics and Gravity Forms

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give-Google-Analytics#22]
## User Story
As a site admin, I want the Give Google Analytics addon to not conflict with Gravity Forms.

## Current Behavior
When Gravity Forms has conditional logic or signature fields present in a form, and Give Google Analytics is installed, activated, and configured. It breaks the form from being loaded.
You will also see a JS error in the console.

<img width="833" alt="screen shot 2018-03-13 at 12 16 46 pm" src="https://user-images.githubusercontent.com/20672471/37354612-731cef08-26b8-11e8-8239-086df8c4a080.png">

## Expected Behavior
I expect to use these two plugins side by side.

## Steps to Reproduce
1. Install Give, Give Google Analytics addon, and Gravity Forms
2. When you install Give Google Analytics make sure that you enable the settings in the Give settings menu.
3. Make a Gravity form that has both fields that load conditionally and signature fields.
4. Access this form using an incognito window (not logged in) and notice that the page won't load the Gravity form.

## Visuals
https://youtu.be/krI4V_rKpTA

## Tasks
- [ ] Enter at least one task to be completed in the [imperative mood](https://chris.beams.io/posts/git-commit/#imperative).

## Environment
<details>
    ### WordPress Environment ###

Home URL: http://ticket-test.local
Site URL: http://ticket-test.local
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: ticket-test.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.4
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://ticket-test.local/donation-confirmation/
Failure Page: http://ticket-test.local/donation-failed/
Donation History Page: http://ticket-test.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Form Field Manager: ❌ Unlicensed – by WordImpress – 1.2.6
Give - Google Analytics Donation Tracking: ❌ Unlicensed – by WordImpress – 1.1.1

### Other Active Plugins ###

Gravity Forms: by rocketgenius – 2.2.6
Gravity Forms Coupons Add-On: by rocketgenius – 2.6
Gravity Forms Dropbox Add-On: by rocketgenius – 2.0
Gravity Forms MailChimp Add-On: by rocketgenius – 4.2
Gravity Forms Partial Entries: by rocketgenius – 1.0
Gravity Forms Signature Add-On: by Rocketgenius – 3.4
Gravity Forms Stripe Add-On: by rocketgenius – 2.4.1
Gravity Forms Zapier Add-on: by rocketgenius – 2.1

### Inactive Plugins ###

Give Simple Ticket Incrementer: by GiveWP.com –
Gravity Forms Event Tracking: by Ronald Huereca – 2.1.0

### Theme ###

Name: Agency Pro
Version: 3.1.5
Author URL: https://www.studiopress.com/
Child Theme: Yes
Parent Theme Name: Genesis
Parent Theme Version: 2.5.3
Parent Theme Author URL: https://www.studiopress.com/

</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Chrome</li>        
    </ul>
</details>

**Comment by raftaar1191** [comment]
Gravity Form Plugin Github Link: https://github.com/wp-premium/gravityforms

**Comment by raftaar1191** [comment]
This issues was coming because of the following comment https://github.com/WordImpress/Give-Google-Analytics/commit/7e30e52d4d8f8085d3729973595ead8cf1288ccc
