### ISSUE TITLE
Also need to send an item to GA.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give-Google-Analytics#3]
GA ecommerce is really designed for something with a cart, so it splits ecommerce data into Transactions (the entire grand total) and Items (each item in the cart).

Since we don't have a cart, we'll need to make the decision about how to handle items. This page shows the different keys available on Google's side: https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce

The current version of our add-on doesn't deal in *items* at all, just with *transactions*. The limitation there is that we only then have ID, affliliation, and Revenue to send, (since we don't have tax or shipping).

I'm adding a PR later that addresses this, by also sending an item, which includes the Form name.

**Comment by Benunc** [comment]
need to address forward compatibility on this. reopening for now. 

Main concern is that if we add functionality to split one transaction over multiple forms, we want to be able to make the code here as forward-compatible to that as possible.

**Comment by DevinWalker** [comment]
Since we're using Enhanced Ecommerce we don't have to worry about _items_ anymore.
