### ISSUE TITLE
fix(google-analytics): prevent $1000.00 donations from reporting as $1 donations at Google

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give-Google-Analytics#35]
## User Story
As a `give admin` or `marketer` I want `Google analytics to report the correct amount for 4+ digit donations` so that `my revenue and e-commerce data is correct.`

## Current behavior
Currently, a $1000.00 donation is reporting to Google as a $1.00 donation, and a $5000.00 donation is reporting as $5.00

## Steps to replicate 
1. Install, activate, and configure Google analytics
2. Make a donation for $1000 (as far as I can tell, default decimal settings work to reproduce)
3. Check in GA, and it reports as $1.

**Comment by ravinderk** [comment]
Working Screenshots :

![image](https://user-images.githubusercontent.com/1784821/44768816-22a1e900-ab80-11e8-9551-148fbd7f4653.png)

![image](https://user-images.githubusercontent.com/1784821/44768816-22a1e900-ab80-11e8-9551-148fbd7f4653.png)

**Comment by Benunc** [comment]
@ravinderk I have replicated twice now, and the user has two large donations not counted correctly.
<img width="712" alt="screen shot 2018-08-29 at 6 47 46 am" src="https://user-images.githubusercontent.com/9629102/44783176-8a900980-ab57-11e8-87e3-e9f49f086d78.png">
<img width="747" alt="screen shot 2018-08-29 at 6 46 50 am" src="https://user-images.githubusercontent.com/9629102/44783191-92e84480-ab57-11e8-9ac3-0ea01cd9877a.png">
<img width="626" alt="screen shot 2018-08-29 at 6 51 04 am" src="https://user-images.githubusercontent.com/9629102/44783316-f1adbe00-ab57-11e8-8e55-46615eeb58c8.png">

Does you closing this mean that it is resolved in the current version (unreleased) or that you weren't able to replicate? 

<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: https://livegive.wpsteward.com
Site URL: https://livegive.wpsteward.com
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_8138bfdc07_
Table Prefix Length: 14
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: livegive.wpsteward.com
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.34 (Unix) OpenSSL/1.0.1f
PHP Version: 7.0.31
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
PHP Max Upload Size: 512 MB
cURL Version: ❌ 7.35.0, OpenSSL/1.0.1f - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.61 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.3
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.2.1
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://livegive.wpsteward.com/donation-confirmation/
Failure Page: https://livegive.wpsteward.com/transaction-failed/
Donation History Page: https://livegive.wpsteward.com/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: PayPal Website Payments Pro (REST API), PayPal Standard, Stripe - Credit Card
Default Payment Gateway: PayPal Website Payments Pro (REST API)
PayPal IPN Verification: Enabled
PayPal IPN Notifications: IPN received for #1008 ( 1KF8642795180635M ) on 08/24/2018 at 16:49. Status VERIFIED
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ✔ Licensed – by WordImpress – 1.4.2
Give - Fee Recovery: ✔ Licensed – by WordImpress – 1.7.1
Give - Google Analytics Donation Tracking: ✔ Licensed – by WordImpress – 1.2.0
Give - Manual Donations: ✔ Licensed – by WordImpress – 1.4.1
Give - PayPal Pro Gateway: ✔ Licensed – by WordImpress – 1.1.6
Give - PDF Receipts: ✔ Licensed – by WordImpress – 2.3
Give - Recurring Donations: ✔ Licensed – by WordImpress – 1.7.2
Give - Stripe Gateway: ✔ Licensed – by WordImpress – 2.0.10
Give - Tributes: ✔ Licensed – by WordImpress – 1.5.0
Give - Zapier: ✔ Licensed – by WordImpress – 1.2.1

### Other Active Plugins ###

Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.1.0
User Switching: by John Blackbourn & contributors – 1.3.1

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.0.8
Email Cop: by Ashfame – 0.1.1
Give - Database HealthCheck: by WordImpress – 0.0.2
Give - Mollie Gateway: by WordImpress – 1.1.1
Hello Dolly: by Matt Mullenweg – 1.6
Page Builder by SiteOrigin: by SiteOrigin – 2.8.2
RegistrationMagic Premium: by Registrationmagic – 3.8.1.7
Restrict Content Pro: by Restrict Content Pro Team – 2.9.10
Series Engine: by Eric Murrell (Volacious) – 2.6.1
SiteOrigin Widgets Bundle: by SiteOrigin – 1.12.1
The GDPR Framework: by Codelight – 1.0.11
WonderPlugin Tabs: by Magic Hills Pty Ltd – 5.8

### Active MU Plugins ###

api-hacks.php: by  –

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by Benunc** [comment]
nope! missed that detail. THanks!

**Comment by ravinderk** [comment]
Closing issue as per discussion on slack: https://givewp.slack.com/archives/C0FAGC83C/p1535540924000100
