### ISSUE TITLE
Why I don't still see any ecommerce in GA?

### ISSUE THREAD

**Issue by namtrok** [WordImpress/Give-Google-Analytics#8]
Hey there,

I've written you en email and got awesome response from you unfortunately the plugin doesn't work on our client website. We tried to uninstall all our plugins but still don't see it in GA.

this is the email I received from you:

> In looking at your site, it looks like you are using enhanced ecommerce from Google Analytics, and the current implementation of our (still very beta) ecommerce analytics add-on is not set up for that. In your Analytics tracking code I see ga("require", "ec", "ec.js"); when it should not be requiring that. Our add-on is requiring the ecommerce.js file from Google, and using both at the same time causes issues, according to Google's documentation. I've started a github issue for that on the GitHub repo for that add-on. This is excellent feedback for us.
> 
> In the short term, you need to remove that line from your tracking code, and see if that causes the add-on to begin functioning. Keep in mind that these ecommerce events are not recorded in real time, and need to be checked the next day.

we've figured out we use plugin for enhanced ecccommerce so we deactivated it but still don't see any results. Could you help me to figure out?

This is the client website http://businessconnectworld.com/

You also asked 

> I'd love to know what Google analytics WordPress plugin you are using, and the various options for eccommerce within it.

We are using only:
- WooCommerce Google Analytics Integration

Thanks,
 Paul

**Comment by mathetos** [comment]
HI Paul,

Sounds like you have an open ticket with our Support team. Let's keep that conversation going over there. This repo is for contributing code directly to the plugin. Thanks!
