### ISSUE TITLE
Define plugin setting with new setting api (Give version 1.8)

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give-Google-Analytics#9]

**Comment by DevinWalker** [comment]
@ravinderk is there an issue this is causing that required immediate release? I merged the PR.

**Comment by ravinderk** [comment]
@DevinWalker this was not causing any issue, but I want to use latest setting API instead.

**Comment by DevinWalker** [comment]
Ok thanks, I'll just set it for the next release then since it's not adding/removing/fixing anything.
